dist: trusty
language: ruby
script: "bundle exec rspec"
sudo: false
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - 2.3.0
  - rbx
  - jruby-head
matrix:
  allow_failures:
    - rvm: 2.4.0
    - rvm: rbx
    - rvm: jruby-head
