dist: trusty
language: ruby
sudo: false
cache:
  - bundler
script: bundle exec rspec
rvm:
  - 2.0.0
  - 2.1.1
  - 2.2.0
  - 2.3.0
  - rbx
  - jruby-head
matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.4.0
    - rvm: rbx
    - rvm: jruby-head
